model: sage
num_layers: 5
hidden_channels: 256
dropout: 0.5

log_steps: 1
lr: 0.001
wd: 0.0
epochs: 500
runs: 1

JK: True
mode: "cat" # no use

use_virtual: True
cluster_method: "metis" 
num_parts: 16 # 16, 128
sparse_ratio: 0.5 