model: sage
num_layers: 3
hidden_channels: 256
dropout: 0.5

log_steps: 1
lr: 0.01
wd: 0.0
epochs: 500
runs: 1

mode: "max" # no use

use_virtual: True
cluster_method: "metis" 
num_parts: 64
sparse_ratio: 1.0 