model: sage # sage, gcn
num_layers: 3
hidden_channels: 256
dropout: 0.5

log_steps: 1
lr: 0.001
wd: 0.0
epochs: 500
runs: 1

mode: "max" # no use

use_virtual: True
cluster_method: "metis" 
num_parts: 128 # 16, 64(72.3, 500 epoch; 72.73, 1000 epoch), 128(72.48, 1000 epoch; 72.20, 500 epoch; no cross cluster, 72.22, 1000 epoch)
sparse_ratio: 0.5 